// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlul4mftI7HHJnj48I2aUs2nV154x0iI',
    appId: '1:452230213864:web:4fe28f71a8044a883d995d',
    messagingSenderId: '452230213864',
    projectId: 'oqcreport-87e5a',
    authDomain: 'oqcreport-87e5a.firebaseapp.com',
    storageBucket: 'oqcreport-87e5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfAW6QaSjhJEcoT0kfUGqbFJaJr4L4CFE',
    appId: '1:452230213864:android:3a9820bb02ecfaa23d995d',
    messagingSenderId: '452230213864',
    projectId: 'oqcreport-87e5a',
    storageBucket: 'oqcreport-87e5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDO6Y_ratDC0waHhuiHCnd1IYlZnZ95Jc',
    appId: '1:452230213864:ios:6605b072dffc18f73d995d',
    messagingSenderId: '452230213864',
    projectId: 'oqcreport-87e5a',
    storageBucket: 'oqcreport-87e5a.firebasestorage.app',
    iosBundleId: 'com.zerova.zerovaOqcReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDO6Y_ratDC0waHhuiHCnd1IYlZnZ95Jc',
    appId: '1:452230213864:ios:6605b072dffc18f73d995d',
    messagingSenderId: '452230213864',
    projectId: 'oqcreport-87e5a',
    storageBucket: 'oqcreport-87e5a.firebasestorage.app',
    iosBundleId: 'com.zerova.zerovaOqcReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzlul4mftI7HHJnj48I2aUs2nV154x0iI',
    appId: '1:452230213864:web:5fbcf1e35d8b5a003d995d',
    messagingSenderId: '452230213864',
    projectId: 'oqcreport-87e5a',
    authDomain: 'oqcreport-87e5a.firebaseapp.com',
    storageBucket: 'oqcreport-87e5a.firebasestorage.app',
  );
}
